Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,21 +55,35 @@ jobs:
           MAINTENANCE_TIME: ${{ github.event.inputs.maintenance_time }}
           BASTION_HOST_IP: ${{ env.BASTION_HOST_IP }}
         run: |
+          if [ ! -f instance_ips.txt ]; then
+            echo "File instance_ips.txt not found!"
+            exit 1
+          fi
+
           INSTANCE_IPS=$(cat instance_ips.txt)
-          
           IFS=$'\n' read -rd '' -a IP_ARRAY <<< "$INSTANCE_IPS"
 
-          for INSTANCE_IP in "${IP_ARRAY[@]}"; do
-            echo "Updating maintenance mode on instance with IP: ${INSTANCE_IP}"
+          if [ ${#IP_ARRAY[@]} -eq 0 ]; then
+            echo "No IPs found in the file."
+            exit 1
+          fi
 
+          for INSTANCE_IP in "${IP_ARRAY[@]}"; do
+            echo "Attempting SSH connection to Bastion Host..."
             ssh -A -o StrictHostKeyChecking=no ubuntu@${BASTION_HOST_IP} << EOF
+              echo "Connected to Bastion Host."
+              echo "Attempting SSH connection to EC2 instance ${INSTANCE_IP}..."
               ssh -i "Web_Server_key.pem" ubuntu@${INSTANCE_IP} << 'EC2EOF'
               
+              echo "Connected to EC2 instance ${INSTANCE_IP}."
+
               if [ "${ACTION}" == "down" ]; then
+                echo "Setting maintenance mode down..."
                 sudo sed -i "s/MAINTENANCE_TIME/${MAINTENANCE_TIME}/g" /var/www/php-laravel-crud/config/maintenance.php
                 sudo systemctl start nginx
 
               elif [ "${ACTION}" == "up" ]; then
+                echo "Removing maintenance mode..."
                 sudo systemctl stop nginx
                 sudo sed -i "s/${MAINTENANCE_TIME}/MAINTENANCE_TIME/g" /var/www/php-laravel-crud/config/maintenance.php
 
@@ -77,5 +91,6 @@ jobs:
                 echo "Invalid action: ${ACTION}"
                 exit 1
               fi
+              EC2EOF
             EOF
-          
+          done
